use wiprodb;

--CREATING TABLE

CREATE TABLE BOooks(
	BookID INT PRIMARY KEY,
	Title VARCHAR(100),
	Author VARCHAR(100),
	Genre VARCHAR(50),
	Price DECIMAL(8,2),
	PublishedYear INT
);

--RENAMING THE TABLE NAME
EXEC sp_rename 'BOooks','Books';

--CURD OPERATIONS

INSERT INTO BOOKS VALUES (1,'The Amazing weather', 'Toni', 'fICTION', 2500.00, 2025),
(2,'THE ALCHEMIST', 'PAULO COELHO', 'fICTION', 299.00, 1003),
(3,'CLEAN CODE', 'ROBERT C. MARTIN', 'PROGRAMMING', 799.00, 2008),
(4,'SAPIENS', 'NOAH', 'HISTORY', 599.00, 2015);

SELECT * FROM BOOKS;

SELECT * FROM BOOKS
WHERE PRICE>2000;

UPDATE BOOKS
SET GENRE='NOVE'
WHERE TITLE='The Amazing weather';

DELETE FROM BOOKS
WHERE PublishedYear<2008;