use wiprodb;

--CREATING STUDENTS TABLE

create table Students(
	StudentID INT PRIMARY KEY,
	FirstName VARCHAR(50),
	Maarks INT,
	DOB DATE
);

INSERT INTO Students (StudentID, FirstName,Maarks, DOB) 
VALUES
(1,'AMIT',92,'2002-05-10'),
(2,'NEHA',78,'2002-11-15'),
(3,'RAHUL',61,'2004-01-20'),
(4,'SNEHA',49,'2003-09-01');

SELECT * FROM STUDENTS;

--CREATING EMPLOYEES TABLE

create table Employees(
	EmpID INT PRIMARY KEY,
	Name VARCHAR(50),
	Department VARCHAR(50),
	Salary DECIMAL(10,2),
	joinDate DATE
);

INSERT INTO Employees (EmpID, Name, Department, Salary, joinDate)
VALUES
(1,'JOHN','HR',50000,'2021-06-01'),
(2,'PRIYA','FINANCE',60000,'2020-09-15'),
(3,'AMIT','IT',15000,'2019-01-10'),
(4,'SARA','IT',72000,'2023-02-25');

SELECT * FROM EMPLOYEES;

--SCALAR FUNCTIONS

SELECT FIRSTNAME, UPPER(FIRSTNAME) AS UPPERNAME FROM STUDENTS;

SELECT FIRSTNAME, DATEDIFF(YEAR, DOB, GETDATE()) AS AGE FROM STUDENTS;

SELECT NAME, ROUND(SALARY, -3) AS ROUNDEDSALARY FROM EMPLOYEES;

--AGGREGATE FUNCTIONS

SELECT COUNT(*) AS TOTALSTUDENTS FROM STUDENTS;

SELECT AVG(Maarks) AS AVERAGEMARKS FROM STUDENTS;

SELECT DEPARTMENT, MAX(SALARY) AS HIGHESTSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- CASE EXPRESSION

SELECT FIRSTNAME, MAARKS,
	CASE
		WHEN MAARKS>=90 THEN 'A'
		WHEN MAARKS>=77 THEN 'B'
		WHEN MAARKS>=60 THEN 'C'
		ELSE 'D'
	END AS GRADE
FROM STUDENTS;

SELECT NAME, SALARY,
	CASE
		WHEN SALARY>=70000 THEN 'HIGH'
		WHEN SALARY>=50000 THEN 'MEDIUM'
		ELSE 'LOW'
	END AS SALARYBAND
FROM EMPLOYEES;

--CHANGING COLUM NAME OF MAARKS COLUMN IN STUDENTS TABLE TO MARKS
EXEC sp_rename 'STUDENTS.MAARKS','MARKS','COLUMN';

