SELECT * FROM EMPLOYEES;

-- TRANSACTION

BEGIN TRANSACTION;

UPDATE EMPLOYEES SET SALARY = SALARY +2000
WHERE DEPARTMENT = 'IT';

COMMIT;

--ROLLBACK

BEGIN TRANSACTION;

DELETE FROM STUDENTS WHERE MARKS<60;

ROLLBACK;

--SAVEPOINT

BEGIN TRANSACTION

UPDATE EMPLOYEES SET SALARY=SALARY+1000
WHERE EMPID=1;

SAVE TRANSACTION INCREASEJOHN;

UPDATE EMPLOYEES SET SALARY = SALARY + 1000
WHERE EMPID=2;

ROLLBACK TRANSACTION INCREASEJOHN;

COMMIT;

--WINDOW FUNCTION

SELECT NAME, DEPARTMENT, SALARY, AVG(SALARY) OVER() AS AVGSALARY
FROM EMPLOYEES;

SELECT NAME, DEPARTMENT, SALARY, AVG(SALARY) OVER(PARTITION BY DEPARTMENT) AS DEPTAVGSALARY
FROM EMPLOYEES;

SELECT NAME, DEPARTMENT, SALARY, ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROWNUM
FROM EMPLOYEES;

SELECT NAME, SALARY, RANK() OVER(ORDER BY SALARY DESC) AS RANKBYSALARY
FROM EMPLOYEES;

--DCL COMMANDS

CREATE USER TEST_USER FOR LOGIN TEST_LOGIN 
CREATE LOGIN TEST_LOGIN WITH PASSWORD = 'STRONGPW123';